# Generated by Django 5.2.4 on 2025-09-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedpang', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='students',
            name='name_prefix',
            field=models.CharField(choices=[('นาย', 'นาย'), ('นางสาว', 'นางสาว'), ('นาง', 'นาง')], max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='stuid',
            field=models.BigIntegerField(unique=True),
        ),
    ]
